# Generated by Django 5.2.6 on 2025-09-08 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=30)),
                ('bike_make', models.CharField(max_length=30)),
                ('bike_model', models.CharField(max_length=30)),
                ('bike_year', models.IntegerField()),
                ('bike_discipline', models.CharField(choices=[('XC', 'Mountain'), ('Trail', 'Electric Mountain'), ('Enduro', 'Enduro'), ('DH', 'Downhill'), ('Park', 'Park'), ('Gravel', 'Gravel'), ('Road', 'Road'), ('DJ', 'Dirt Jumper')], max_length=30)),
                ('bike_type', models.CharField(choices=[('MTB', 'Mountain'), ('E-MTB', 'Electric Mountain'), ('Gravel', 'Gravel'), ('Road', 'Road'), ('DJ', 'Dirt Jumper')], max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ll_buildbike.llbike')),
            ],
        ),
    ]
