# Generated by Django 5.2.6 on 2025-09-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll_buildbike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llbike',
            name='bike_img',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
    ]
