# Generated by Django 5.2.6 on 2025-09-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll_buildbike', '0002_llbike_bike_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='llbike',
            name='bike_build',
            field=models.CharField(blank=True, choices=[('Stock', 'Stock'), ('Upgraded', 'Upgraded'), ('GroundUpBuild', 'Ground Up Build'), ('PartsBike', 'Parts Bike')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llbike',
            name='bike_discipline',
            field=models.CharField(blank=True, choices=[('XC', 'Mountain'), ('Trail', 'Electric Mountain'), ('Enduro', 'Enduro'), ('DH', 'Downhill'), ('Park', 'Park'), ('Gravel', 'Gravel'), ('Road', 'Road'), ('DJ', 'Dirt Jumper')], max_length=30, null=True),
        ),
    ]
