# Generated by Django 5.2.6 on 2025-09-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll_buildbike', '0003_llbike_bike_build_alter_llbike_bike_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llbike',
            name='bike_make',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='llbike',
            name='bike_model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='llbike',
            name='bike_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='llbike',
            unique_together={('bike_name', 'bike_make', 'bike_model', 'bike_year')},
        ),
    ]
