# Generated by Django 5.2.6 on 2025-09-16 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll_buildbike', '0004_alter_llbike_bike_make_alter_llbike_bike_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llbike',
            name='bike_img',
        ),
        migrations.AlterField(
            model_name='llbike',
            name='bike_discipline',
            field=models.CharField(blank=True, choices=[('XC', 'Cross-Country'), ('Trail', 'Trail'), ('Enduro', 'Enduro'), ('DH', 'Downhill'), ('Park', 'Park'), ('Gravel', 'Gravel'), ('Road', 'Road'), ('DJ', 'Dirt Jumper')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='LLBikeImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_img', models.ImageField(blank=True, null=True, upload_to='bike_images/')),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ll_buildbike.llbike')),
            ],
        ),
    ]
