# Generated by Django 5.2.6 on 2025-09-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll_buildbike', '0005_remove_llbike_bike_img_alter_llbike_bike_discipline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llcomponent',
            name='bike_id',
        ),
        migrations.AlterField(
            model_name='llbike',
            name='bike_type',
            field=models.CharField(blank=True, choices=[('MTB', 'Mountain'), ('E-MTB', 'Electric Mountain'), ('Gravel', 'Gravel'), ('Road', 'Road'), ('DJ', 'Dirt Jumper')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='LLBikeImg',
        ),
        migrations.DeleteModel(
            name='LLComponent',
        ),
    ]
