# Generated by Django 5.2.6 on 2025-09-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll_buildbike', '0008_llcomponentbrakes_llcomponentcockpit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llcomponentbrakes',
            name='bike_brakes_actuation',
        ),
        migrations.RemoveField(
            model_name='llcomponentcockpit',
            name='bike_stem',
        ),
        migrations.AddField(
            model_name='llcomponentbrakes',
            name='bike_brakelevers_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='llcomponentbrakes',
            name='bike_brakelevers_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='llcomponentbrakes',
            name='bike_brakepads_makemodel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='llcomponentbrakes',
            name='bike_brakepads_material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='bike_shifter_speed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='bike_stem_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='bike_stem_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llbike',
            name='bike_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llbike',
            name='bike_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llbike',
            name='bike_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llbike',
            name='bike_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentbrakes',
            name='bike_brakerotor_attach',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentbrakes',
            name='bike_brakerotor_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentbrakes',
            name='bike_brakerotor_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentbrakes',
            name='bike_brakerotor_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentbrakes',
            name='bike_brakes_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentbrakes',
            name='bike_brakes_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentbrakes',
            name='bike_brakes_pistons',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_bars_diam',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_bars_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_bars_material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_bars_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_bars_rise',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_bars_width',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_brakelevers_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_brakelevers_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_dropperlever_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_dropperlever_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_grips_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_grips_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_headset_bottom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_headset_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_headset_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_headset_top',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_headset_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_shifter_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_shifter_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_stem_length',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_stem_opening',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_stem_stack',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_bottombracket_fitment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_bottombracket_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_bottombracket_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_bottombracket_width',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cassette_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cassette_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cassette_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cassette_speed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cassette_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_chain_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_chain_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_chain_speed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_chainring_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_chainring_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_chainring_teeth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cranks_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cranks_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cranks_material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cranks_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_derailleur_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_derailleur_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_derailleur_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_pedals_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_pedals_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_pedals_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentseat',
            name='bike_saddle_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentseat',
            name='bike_saddle_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentseat',
            name='bike_seatpost_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentseat',
            name='bike_seatpost_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentseat',
            name='bike_seatpost_travel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentseat',
            name='bike_seatpost_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentseat',
            name='bike_seatpost_width',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_frontsus_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_frontsus_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_frontsus_travel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_frontsus_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_rearsus_eyetoeye',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_rearsus_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_rearsus_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_rearsus_travel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_rearsus_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_fronttire_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_fronttire_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_fronttire_quality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_fronttire_width',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_hubs_axle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_hubs_eng',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_hubs_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_hubs_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_hubs_width',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_reartire_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_reartire_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_reartire_quality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_reartire_width',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_rims_holecount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_rims_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_rims_material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_rims_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_rims_size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
