# Generated by Django 5.2.6 on 2025-09-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll_buildbike', '0009_remove_llcomponentbrakes_bike_brakes_actuation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llcomponentwheel',
            name='bike_hubs_width',
        ),
        migrations.AddField(
            model_name='llcomponentbrakes',
            name='bike_brakelevers_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your brake levers?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentbrakes',
            name='bike_brakelevers_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentbrakes',
            name='bike_brakepads_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your brake pads?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentbrakes',
            name='bike_brakepads_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentbrakes',
            name='bike_brakerotor_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your brake rotor?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentbrakes',
            name='bike_brakerotor_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentbrakes',
            name='bike_brakes_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your brakes?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentbrakes',
            name='bike_brakes_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='bike_bars_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your bars?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='bike_bars_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='bike_brakelevers_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your brake levers?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='bike_brakelevers_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='bike_dropperlever_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your dropper lever?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='bike_dropperlever_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='bike_grips_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your grips?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='bike_grips_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='bike_headset_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your headset?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='bike_headset_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='bike_shifter_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your shifter?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='bike_shifter_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='bike_stem_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your stem?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='bike_stem_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentdrive',
            name='bike_bottombracket_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your bottom bracket?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentdrive',
            name='bike_bottombracket_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentdrive',
            name='bike_cassette_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your cassette?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentdrive',
            name='bike_cassette_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentdrive',
            name='bike_chain_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your chain?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentdrive',
            name='bike_chain_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentdrive',
            name='bike_chainring_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your chainring?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentdrive',
            name='bike_chainring_bcd',
            field=models.CharField(blank=True, help_text='What is the BCD of your chainring?', max_length=100, verbose_name='Chainring BCD'),
        ),
        migrations.AddField(
            model_name='llcomponentdrive',
            name='bike_chainring_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentdrive',
            name='bike_cranks_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your cranks?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentdrive',
            name='bike_cranks_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentdrive',
            name='bike_derailleur_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your derailleur?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentdrive',
            name='bike_derailleur_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentdrive',
            name='bike_derailleur_type',
            field=models.CharField(blank=True, help_text='Ex: Electronic, Mechanical?', max_length=100, verbose_name='Derailleur Type'),
        ),
        migrations.AddField(
            model_name='llcomponentdrive',
            name='bike_pedals_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your pedals?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentdrive',
            name='bike_pedals_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentseat',
            name='bike_saddle_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your saddle?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentseat',
            name='bike_saddle_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentseat',
            name='bike_seatpost_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your seatpost?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentseat',
            name='bike_seatpost_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentsus',
            name='bike_frontsus_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your front suspension?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentsus',
            name='bike_frontsus_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentsus',
            name='bike_rearsus_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your rear suspension?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentsus',
            name='bike_rearsus_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentwheel',
            name='bike_complete_wheel_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your complete wheel?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentwheel',
            name='bike_complete_wheel_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='llcomponentwheel',
            name='bike_complete_wheel_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='llcomponentwheel',
            name='bike_complete_wheel_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentwheel',
            name='bike_complete_wheel_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='llcomponentwheel',
            name='bike_complete_wheel_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='llcomponentwheel',
            name='bike_fronttire_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your front tire?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentwheel',
            name='bike_fronttire_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentwheel',
            name='bike_hubs_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your hubs?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentwheel',
            name='bike_hubs_frontwidth',
            field=models.CharField(blank=True, help_text='Ex: 15 x 110, etc.', max_length=100, verbose_name='Front Hub Width (mm)'),
        ),
        migrations.AddField(
            model_name='llcomponentwheel',
            name='bike_hubs_rearwidth',
            field=models.CharField(blank=True, help_text='Ex: 12 x 148, etc.', max_length=100, verbose_name='Rear Hub Width (mm)'),
        ),
        migrations.AddField(
            model_name='llcomponentwheel',
            name='bike_hubs_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentwheel',
            name='bike_reartire_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your rear tire?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentwheel',
            name='bike_reartire_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llcomponentwheel',
            name='bike_rims_addtnotes',
            field=models.TextField(blank=True, help_text='Any additional notes about your rims?', max_length=500, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='llcomponentwheel',
            name='bike_rims_review',
            field=models.CharField(blank=True, choices=[('5', '(U+2605) (U+2605) (U+2605) (U+2605) (U+2605)'), ('4', '(U+2605) (U+2605) (U+2605) (U+2605)'), ('3', '(U+2605) (U+2605) (U+2605)'), ('2', '(U+2605) (U+2605)'), ('1', '(U+2605)')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_bottombracket_fitment',
            field=models.CharField(blank=True, help_text='Ex: BSA, Press Fit, etc.', max_length=100, verbose_name='Bottom Bracket Fitment'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_bottombracket_make',
            field=models.CharField(blank=True, help_text='Who makes your bottom bracket?', max_length=100, verbose_name='Bottom Bracket Make'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_bottombracket_model',
            field=models.CharField(blank=True, help_text='What model is your bottom bracket?', max_length=100, verbose_name='Bottom Bracket Model'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_bottombracket_width',
            field=models.CharField(blank=True, help_text='Ex: 68, 73, etc.', max_length=100, verbose_name='Bottom Bracket Width (mm)'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cassette_make',
            field=models.CharField(blank=True, help_text='Who makes your cassette?', max_length=100, verbose_name='Cassette Make'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cassette_model',
            field=models.CharField(blank=True, help_text='What model is your cassette?', max_length=100, verbose_name='Cassette Model'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cassette_range',
            field=models.CharField(blank=True, help_text='Range is smallest # of teeth to largest # of teeth (ex: 10-50T).', max_length=100, verbose_name='Cassette Range'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cassette_speed',
            field=models.PositiveIntegerField(blank=True, help_text='How many speeds (or separate rings) does your cassette have?', null=True, verbose_name='Cassette Speed'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cassette_year',
            field=models.PositiveIntegerField(blank=True, help_text='What year is your cassette?', null=True, verbose_name='Cassette Year'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_chain_make',
            field=models.CharField(blank=True, help_text='Who makes your chain?', max_length=100, verbose_name='Chain Make'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_chain_model',
            field=models.CharField(blank=True, help_text='What model is your chain?', max_length=100, verbose_name='Chain Model'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_chain_speed',
            field=models.PositiveIntegerField(blank=True, help_text='Ex: 9, 10, 11, etc.', null=True, verbose_name='Chain Speed'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_chainring_make',
            field=models.CharField(blank=True, help_text='Who makes your chainring?', max_length=100, verbose_name='Chainring Make'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_chainring_model',
            field=models.CharField(blank=True, help_text='What model is your chainring?', max_length=100, verbose_name='Chainring Model'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_chainring_teeth',
            field=models.PositiveIntegerField(blank=True, help_text='How many teeth does your chainring have?', null=True, verbose_name='Chainring Teeth'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cranks_length',
            field=models.PositiveIntegerField(blank=True, help_text='(Ex: 170, 175, etc.)', null=True, verbose_name='Crank Length (mm)'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cranks_make',
            field=models.CharField(blank=True, help_text='Who makes your cranks?', max_length=100, verbose_name='Crank Make'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cranks_material',
            field=models.CharField(blank=True, help_text='(Ex: Aluminum, Carbon, etc.)', max_length=100, verbose_name='Crank Material'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cranks_model',
            field=models.CharField(blank=True, help_text='What model is your cranks?', max_length=100, verbose_name='Crank Model'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_derailleur_make',
            field=models.CharField(blank=True, help_text='Who makes your derailleur?', max_length=100, verbose_name='Derailleur Make'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_derailleur_model',
            field=models.CharField(blank=True, help_text='What model is your derailleur?', max_length=100, verbose_name='Derailleur Model'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_derailleur_year',
            field=models.PositiveIntegerField(blank=True, help_text='What year is your derailleur?', null=True, verbose_name='Derailleur Year'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_pedals_make',
            field=models.CharField(blank=True, help_text='Who makes your pedals?', max_length=100, verbose_name='Pedal Make'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_pedals_model',
            field=models.CharField(blank=True, help_text='What model are your pedals?', max_length=100, verbose_name='Pedal Model'),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_pedals_type',
            field=models.CharField(blank=True, help_text='Ex: Clipless, Flat, etc.', max_length=100, verbose_name='Pedal Type'),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_frontsus_make',
            field=models.CharField(blank=True, help_text='Who makes your fork?', max_length=100, verbose_name='Front Suspension Make'),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_frontsus_model',
            field=models.CharField(blank=True, help_text='What model is your fork?', max_length=100, verbose_name='Front Suspension Model'),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_frontsus_travel',
            field=models.CharField(blank=True, help_text='How much travel does your fork have?', max_length=100, verbose_name='Front Suspension Travel'),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_frontsus_year',
            field=models.PositiveIntegerField(blank=True, help_text='What year is your fork?', null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_rearsus_eyetoeye',
            field=models.CharField(blank=True, help_text='What is the eye-to-eye length of your rear shock?', max_length=100, verbose_name='Rear Suspension Eye-to-Eye'),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_rearsus_make',
            field=models.CharField(blank=True, help_text='Who makes your rear shock?', max_length=100, verbose_name='Rear Suspension Make'),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_rearsus_model',
            field=models.CharField(blank=True, help_text='What model is your rear shock?', max_length=100, verbose_name='Rear Suspension Model'),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_rearsus_travel',
            field=models.CharField(blank=True, help_text='How much travel does your rear shock have?', max_length=100, verbose_name='Rear Suspension Travel'),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_rearsus_year',
            field=models.PositiveIntegerField(blank=True, help_text='What year is your rear shock?', null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_hubs_axle',
            field=models.CharField(blank=True, help_text='Ex: Thru Axle, QR, etc.', max_length=100, verbose_name='Hub Axle'),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_hubs_eng',
            field=models.CharField(blank=True, help_text='Ex: 36 points, 54 points, etc.', max_length=100, verbose_name='Rear Hub Engagement'),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_hubs_make',
            field=models.CharField(blank=True, help_text='Who makes your hubs?', max_length=100, verbose_name='Hub Make'),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_hubs_model',
            field=models.CharField(blank=True, help_text='What model are your hubs?', max_length=100, verbose_name='Hub Model'),
        ),
    ]
