# Generated by Django 5.2.6 on 2025-09-30 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll_buildbike', '0010_remove_llcomponentwheel_bike_hubs_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llbikeimg',
            name='bike_id',
        ),
        migrations.RemoveField(
            model_name='llcomponentbrakes',
            name='bike_id',
        ),
        migrations.RemoveField(
            model_name='llcomponentcockpit',
            name='bike_id',
        ),
        migrations.RemoveField(
            model_name='llcomponentdrive',
            name='bike_id',
        ),
        migrations.RemoveField(
            model_name='llcomponentseat',
            name='bike_id',
        ),
        migrations.RemoveField(
            model_name='llcomponentsus',
            name='bike_id',
        ),
        migrations.RemoveField(
            model_name='llcomponentwheel',
            name='bike_id',
        ),
        migrations.AddField(
            model_name='llbike',
            name='bike_img',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='llbike',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Default Bike'),
        ),
        migrations.AddField(
            model_name='llbikeimg',
            name='llbike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bike_images', to='ll_buildbike.llbike'),
        ),
        migrations.AddField(
            model_name='llcomponentbrakes',
            name='llbike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brake_components', to='ll_buildbike.llbike'),
        ),
        migrations.AddField(
            model_name='llcomponentcockpit',
            name='llbike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cockpit_components', to='ll_buildbike.llbike'),
        ),
        migrations.AddField(
            model_name='llcomponentdrive',
            name='llbike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivetrain_components', to='ll_buildbike.llbike'),
        ),
        migrations.AddField(
            model_name='llcomponentseat',
            name='llbike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_components', to='ll_buildbike.llbike'),
        ),
        migrations.AddField(
            model_name='llcomponentsus',
            name='llbike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspension_components', to='ll_buildbike.llbike'),
        ),
        migrations.AddField(
            model_name='llcomponentwheel',
            name='llbike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wheel_components', to='ll_buildbike.llbike'),
        ),
    ]
