# Generated by Django 5.2.6 on 2025-10-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll_buildbike', '0012_llbike_like_count_llbike_owner_bikelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llbike',
            name='bike_build',
            field=models.CharField(blank=True, choices=[('Stock', 'Stock'), ('Upgraded', 'Upgraded'), ('GroundUpBuild', 'Ground Up Build'), ('PartsBike', 'Parts Bike')], help_text='What is the build type of your bike?', max_length=30, null=True, verbose_name='Bike Build'),
        ),
        migrations.AlterField(
            model_name='llbike',
            name='bike_discipline',
            field=models.CharField(blank=True, choices=[('XC', 'Cross-Country'), ('Trail', 'Trail'), ('Enduro', 'Enduro'), ('DH', 'Downhill'), ('Park', 'Park'), ('Gravel', 'Gravel'), ('Road', 'Road'), ('DJ', 'Dirt Jumper')], max_length=30, null=True, verbose_name='Bike Discipline'),
        ),
        migrations.AlterField(
            model_name='llbike',
            name='bike_make',
            field=models.CharField(blank=True, help_text='What is the make of your bike?', max_length=100, verbose_name='Bike Make'),
        ),
        migrations.AlterField(
            model_name='llbike',
            name='bike_model',
            field=models.CharField(blank=True, help_text='What is the model of your bike?', max_length=100, verbose_name='Bike Model'),
        ),
        migrations.AlterField(
            model_name='llbike',
            name='bike_name',
            field=models.CharField(blank=True, help_text='What is the name of your bike?', max_length=100, verbose_name='Bike Name'),
        ),
        migrations.AlterField(
            model_name='llbike',
            name='bike_size',
            field=models.CharField(blank=True, choices=[('ExtraSmall', 'Extra Small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('ExtraLarge', 'Extra Large')], help_text='What size is your bike?', max_length=30, null=True, verbose_name='Bike Size'),
        ),
        migrations.AlterField(
            model_name='llbike',
            name='bike_type',
            field=models.CharField(blank=True, choices=[('MTB', 'Mountain'), ('E-MTB', 'Electric Mountain'), ('Gravel', 'Gravel'), ('Road', 'Road'), ('DJ', 'Dirt Jumper')], max_length=30, null=True, verbose_name='Bike Type'),
        ),
        migrations.AlterField(
            model_name='llbike',
            name='bike_year',
            field=models.PositiveIntegerField(blank=True, help_text='What year is your bike?', null=True, verbose_name='Bike Year'),
        ),
    ]
