# Generated by Django 5.2.6 on 2025-10-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll_buildbike', '0013_alter_llbike_bike_build_alter_llbike_bike_discipline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llbike',
            name='bike_discipline',
            field=models.CharField(blank=True, choices=[('XC', 'Cross-Country'), ('Trail', 'Trail'), ('Enduro', 'Enduro'), ('DH', 'Downhill'), ('Park', 'Park'), ('Gravel', 'Gravel'), ('Road', 'Road'), ('DJ', 'Dirt Jumper')], help_text='What type of trails does this bike excel at?', max_length=30, null=True, verbose_name='Bike Discipline'),
        ),
        migrations.AlterField(
            model_name='llbike',
            name='bike_type',
            field=models.CharField(blank=True, choices=[('MTB', 'Mountain'), ('E-MTB', 'Electric Mountain'), ('Gravel', 'Gravel'), ('Road', 'Road'), ('DJ', 'Dirt Jumper')], help_text='What type of bike is it?', max_length=30, null=True, verbose_name='Bike Type'),
        ),
        migrations.AlterField(
            model_name='llbike',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Make this bike the default?'),
        ),
        migrations.AlterField(
            model_name='llcomponentbrakes',
            name='bike_brakelevers_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentbrakes',
            name='bike_brakepads_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentbrakes',
            name='bike_brakerotor_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentbrakes',
            name='bike_brakes_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_bars_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_brakelevers_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_dropperlever_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_grips_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_headset_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_shifter_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentcockpit',
            name='bike_stem_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_bottombracket_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cassette_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_chain_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_chainring_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_cranks_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_derailleur_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentdrive',
            name='bike_pedals_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentseat',
            name='bike_saddle_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentseat',
            name='bike_seatpost_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_frontsus_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentsus',
            name='bike_rearsus_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_complete_wheel_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_fronttire_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_hubs_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_reartire_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='llcomponentwheel',
            name='bike_rims_review',
            field=models.CharField(blank=True, choices=[('5', '★ ★ ★ ★ ★'), ('4', '★ ★ ★ ★'), ('3', '★ ★ ★'), ('2', '★ ★'), ('1', '★')], max_length=30, null=True),
        ),
    ]
