# Generated by Django 5.2.6 on 2025-10-02 13:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll_buildbike', '0014_alter_llbike_bike_discipline_alter_llbike_bike_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llbike',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
