# Generated by Django 5.2.6 on 2025-10-02 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll_buildbike', '0015_llbike_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='llbike',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='llbike',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='uniq_bike_slug_per_owner'),
        ),
    ]
