# Generated by Django 5.2.6 on 2025-10-01 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ll_buildbike', '0012_llbike_like_count_llbike_owner_bikelike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fork_pressure_psi', models.PositiveIntegerField(blank=True, null=True)),
                ('fork_rebound_clicks', models.PositiveIntegerField(blank=True, null=True)),
                ('shock_pressure_psi', models.PositiveIntegerField(blank=True, null=True)),
                ('shock_rebound_clicks', models.PositiveIntegerField(blank=True, null=True)),
                ('tire_front_psi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tire_rear_psi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sections', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='ll_buildbike.llbike')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
